### ISSUE TITLE
Slight error in makefile

### ISSUE THREAD

**Issue by midnqp** [devinsmith/w3m#1]
```
$ make
Makefile:1: *** missing separator.  Stop.
```

**Comment by devinsmith** [comment]
You'll have to use BSD Make on non BSD platforms. On Debian this is in the "bmake" package. The alternative is changing the Makefile to GNU style, or even using something like CMake (although that's a larger scope of work).

**Comment by devinsmith** [comment]
I realized that just using bmake is not enough to get this working as it relies on some specific BSD string functions like `vasprintf`. These are typically provided by `libbsd` but getting this integrated into the build system is looking like a bit of work. I'll keep this issue open until it can be fixed.

**Comment by midnqp** [comment]
Didn't want to create another issue -- just a question: Wikipedia said `w3m` has "partial" Javascript support? So, how did you implement JS?

**Comment by midnqp** [comment]
> I realized that just using bmake is not enough to get this working as it relies on some specific BSD string functions like `vasprintf`. These are typically provided by `libbsd` but getting this integrated into the build system is looking like a bit of work. I'll keep this issue open until it can be fixed.

Okay, how do I integrate `libbsd` to build system? What should I do?

**Comment by devinsmith** [comment]
I've got past the `libbsd` issue for now. The new issue is `libtls` which is a part of OpenBSD's LibreSSL but not usually available on Linux distributions. I am trying to work around that for now.

Also as far as I can tell w3m does not have support for any Javascript, although there is a patch to enable some support.

**Comment by devinsmith** [comment]
As of 9a6900b104356ce7d21c96a3ae5a66a46c960972 you should now be able to build this on Linux based operating systems using CMake. I did some basic testing and it appears to mostly work.

**Comment by midnqp** [comment]
CMake has this issue now: `--   No package 'bdw-gc' found`
And `make` says: `Makefile:1: *** missing separator.  Stop.
`

**Comment by devinsmith** [comment]
You need to install the Boehm GC. Under Debian/Ubuntu it's install-able with "sudo apt-get install libgc-dev". I'm not sure about other distributions.

**Comment by midnqp** [comment]
Great it compiles to executable. But, `w3s` is stuck at "Opening socket..."

**Comment by devinsmith** [comment]
Can you tell me your OS and version you're using. I can try to investigate.
